### ISSUE TITLE
Beim Abschnitt "Setup" Referenz zur Doku

### ISSUE THREAD

**Issue by hsirtl** [joergjo/contosoads-containerapp#3]
Beim Abschnitt zur Erzeugung eines Service Principals ggf. einen Link zur Doku hinzufügen. Z.B. zu https://docs.microsoft.com/en-us/azure/communication-services/quickstarts/identity/service-principal-from-cli

Dieser Link beschreibt (anders als manch andere) auch wie die JSON-Ausgabe aussieht, die man ja in die GitHub-secrets aufnehmen muss.

Die Abschnitte danach beschreiben die einzelnen Schritte zwar, nachdem deren Überschriften aber auf der gleichen Hierarchiestufe wie "Setup" sind, wird nicht gleich klar, dass diese die Setup-Schritte 1 und 2 detaillierter beschreiben.

**Comment by joergjo** [comment]
Thanks! I have changed the markdown structure to make sure 'Authenticate to Azure' and 'Deploy the code' are subsections of 'Setup'. Also added doc link to creating a service principal using Azure CLI.
