### ISSUE TITLE
Expose Azurite to both Docker network and localhost

### ISSUE THREAD

**Issue by joergjo** [joergjo/contosoads-containerapp#30]
## Docker Host Access and Dapr Setup Issues

The Compose setup in this project previously relied on accessing the Docker host's IPv4 address from within the Docker network, allowing both the browser on the host and the Dapr sidecar to access Dapr storage bindings.

However, recent Docker Desktop (for Mac) releases no longer support host access via IPv4 addresses, and this method was likely never intended to work, as only the [host networking driver](https://docs.docker.com/engine/network/drivers/host/#docker-desktop) should provide such access from a container.

### Solution for Azurite Access

To access Azurite, the Dapr sidecar can use the `host.docker.internal` hostname or the Docker service name `azurite`. Unfortunately, these hostnames lead to image URLs that break rendering in the browser, as the host machine cannot resolve them.

### Fix: ASP.NET Core Tag Helper

We will resolve this issue by implementing:
- An [ASP.NET Core tag helper](https://learn.microsoft.com/en-us/aspnet/core/mvc/views/tag-helpers/authoring?view=aspnetcore-8.0) to update `img` tag `src` attributes that use `host.docker.internal` in their URLs.
- A [tag helper initializer](https://learn.microsoft.com/en-us/aspnet/core/mvc/views/tag-helpers/intro?view=aspnetcore-8.0#tag-helper-initializers) to apply the necessary settings across all `img` tags automatically, without modifying individual Razor pages.

A new configuration key `ImageSource:Host` will control the tag helper. When enabled, the tag helper will modify `img` tags using the `host.docker.internal` hostname in its `src` attribute .

### Running Outside Docker

This feature is designed primarily for running the full stack in Docker, but it can also be used when running the application outside of Docker while sharing the same database. In such cases, URLs generated in Docker will need updating for proper image rendering.

**Comment by corrosive4354** [comment]
Test the tag helper: Make sure the tag helper works properly in all situations, including when running inside and outside of Docker.

In addition, it may be a compatibility issue between Docker and Mac environments. You can use [servbay](servbay.com) to solve it, which is better than Docker on Mac.
