### ISSUE TITLE
Fehler beim Anlegen eines Service Principals

### ISSUE THREAD

**Issue by hsirtl** [joergjo/contosoads-containerapp#5]
Die Zeile

```az ad sp create-for-rbac --sdk-auth --name ContosoAds-CICD --role contributor --scopes "/subscriptions/$subscription_id"```

zeigt zumindest bei mir (kann auch einer etwas instabilen Ubuntu-distro liegen) die Warnung

"Option '--sdk-auth' has been deprecated and will be removed in a future release."

an und gibt zudem nicht das benötigte JSON aus.

Erst wenn ich es ohne den SDK-Parameter mache, funktioniert's mit der JSON-Ausgabe:

```az ad sp create-for-rbac --name ContosoAds-CICD --role contributor --scopes "/subscriptions/$s
ubscription_id"```

**Comment by joergjo** [comment]
`--sdk-auth` _is_ actually deprecated, but is still available to support GitHub Actions (see https://github.com/Azure/azure-cli/pull/21219). The output of `az ad sp create-for-rbac` is different from `--sdk-auth`, so I'm surprised that this has worked for -- unless GH actions now support the new condensed JSON output.

**Comment by joergjo** [comment]
I've added a note that the deprecation warning is to be expected right now.

@hsirtl Are you saying that the output of `az ad sp create` worked for you in GH Actions?

**Comment by hsirtl** [comment]
```az ad sp create``` gave all the info needed for the secrets (copying single values to the respective fields in the secrets template, e.g. appID -> clientID). It's fine to have the deprecated warning.
